version: 2.1

orbs:
  docker: circleci/docker@3.3.0

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.16
      - docker/setup-qemu-action@v3
      - docker/setup-buildx-action@v3

      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - docker/build-push:
          platform: linux/amd64,linux/arm64
          push: true
          tags: ozbillwang/demo:latest

workflows:
  build-and-push-workflow:
    jobs:
      - build-and-push

